In [1]:
# diabetes.csv dataset
#Boosting Technique 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#To load dataset diabetes.csv
df=pd.read_csv("diabetes.csv")
#to display first 5 records
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
#select Input X and output Y  from given dataset df
X=df.drop("Outcome",axis=1) #input features
Y=df["Outcome"]#output features

In [4]:
#Train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [5]:
#User defined function
def create_model(model):
    model.fit(X_train,Y_train)  #train the model
    Y_pred=model.predict(X_test) #Test the model
    print(classification_report(Y_test,Y_pred))
    print("Confusion Matrix ")
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [6]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [7]:
#3. Boosting Technique : -
#1. ADA Boost : Adaptor boosting 
#call class
from sklearn.ensemble import AdaBoostClassifier

In [8]:
#create the object of AdaBoostClassifier class 
ada=AdaBoostClassifier(n_estimators=75) #passing arguments n_estimators means no. of iteration
#value of this parameter can be <=100 not more than 100 for any dataset
#not mension algorithm name because understood : decision tree ,its create a decision stump

In [9]:
#call function
ada=create_model(ada)

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       146
           1       0.75      0.59      0.66        85

    accuracy                           0.77       231
   macro avg       0.77      0.74      0.75       231
weighted avg       0.77      0.77      0.77       231

Confusion Matrix 
[[129  17]
 [ 35  50]]


In [10]:
#2. gradient Boost technuique : second tech. of Boosting Ensembling technique 
# GB  : - its create a fully grown tree.this algorithm is focus on short comings 
#short comings means error 

In [11]:
#call inbuilt class GradientBoostingClassifier 
from sklearn.ensemble import GradientBoostingClassifier 

In [12]:
#create the object of GradientBoostingClassifier  class
gbc=GradientBoostingClassifier(n_estimators=75) #here n_estimators can be <=100 
#here n_estimators is inbuilt parameter for iteration 
#GradientBoostingClassifier use always decision tree so not mension alogorithm name

In [13]:
#call function
gbc=create_model(gbc)

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       146
           1       0.76      0.64      0.69        85

    accuracy                           0.79       231
   macro avg       0.78      0.76      0.77       231
weighted avg       0.79      0.79      0.79       231

Confusion Matrix 
[[129  17]
 [ 31  54]]


In [14]:
#call inbuilt class XGBClassifier which define inbuilt package xgboost
from xgboost import XGBClassifier

In [15]:
#create object of XGBClassifier class
xg=XGBClassifier(n_estimators=25,reg_alpha=1) #reg_alpha inbuilt parameter , we pass value 1 means
#to handle automatic overfitting and outlier situation means to overcome the overfitting
#1 means true 

In [16]:
#call function
xg=create_model(xg)

[13:24:09] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       146
           1       0.75      0.62      0.68        85

    accuracy                           0.78       231
   macro avg       0.77      0.75      0.76       231
weighted avg       0.78      0.78      0.78       231

Confusion Matrix 
[[128  18]
 [ 32  53]]
