In [1]:
# diabetes.csv dataset
#Ensembling Technique 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#To load dataset diabetes.csv
df=pd.read_csv("diabetes.csv")
#to display first 5 records
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
#first, check null values in given dataset
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
#datatype check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
#select Input X and output Y  from given dataset df
X=df.drop("Outcome",axis=1) #input features
Y=df["Outcome"]#output features

In [6]:
#Train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [7]:
#User defined function
def create_model(model):
    model.fit(X_train,Y_train)  #train the model
    Y_pred=model.predict(X_test) #Test the model
    print(classification_report(Y_test,Y_pred))
    print("Confusion Matrix ")
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [8]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [9]:
#Ensembling Technique apply :-
#1. Naive Aggregation
#A. Hard Voting : -

#we take 3 types of classification algorithm to train the dataset
#1. Logistic regression  2. Decision tree(Gini index) 3. DecisionTree(Entropy) 
#call Logistic regression class
from sklearn.linear_model import LogisticRegression
#call decisiontreeclassifier class
from sklearn.tree import DecisionTreeClassifier  #DecisionTreeClassifier inbuilt class

In [10]:
#create object of LogisticRegression
lr=LogisticRegression()
#create object of DecisionTreeClassifier with gini index
dt1=DecisionTreeClassifier() #befault gini index
#create object of DecisionTreeClassifier with entropy
dt2=DecisionTreeClassifier(criterion="entropy")

In [11]:
#Hard voting 
#begin with simple one first

#Create a model list
model_list=[("Logistic",lr),("DecisionTree-GiniIndex",dt1),("DecisionTree-Entropy",dt2)]
#here model_list is a user defined list object
'''A List consists of multiple tuples and each tuples the first argument has to be a string 
that is a name of the model and second argument has to be a object of model(algorithm)'''

'A List consists of multiple tuples and each tuples the first argument has to be a string \nthat is a name of the model and second argument has to be a object of model(algorithm)'

In [12]:
#Then we need Naive aggregation
#we importing class
from sklearn.ensemble import VotingClassifier  #VotingClassifier inbuilt class

In [13]:
#create object of VotingClassifier  class
vc1=VotingClassifier(estimators=model_list) #here estimators inbuilt parameter of VotingClassifier  
#class , here pass the model_list in this parameter 
#budefault mension hard voting if no define any parameter for hard voting 

In [14]:
#Let call function create_model
vc1=create_model(vc1)

              precision    recall  f1-score   support

           0       0.78      0.86      0.82       146
           1       0.70      0.59      0.64        85

    accuracy                           0.76       231
   macro avg       0.74      0.72      0.73       231
weighted avg       0.75      0.76      0.75       231

Confusion Matrix 
[[125  21]
 [ 35  50]]


In [15]:
#soft voting 
#create object of VotingClassifier  class
vc2=VotingClassifier(estimators=model_list,voting="soft")#bydefault voting="hard"

In [16]:
#Let call function create_model
vc2=create_model(vc2)

              precision    recall  f1-score   support

           0       0.77      0.85      0.81       146
           1       0.68      0.55      0.61        85

    accuracy                           0.74       231
   macro avg       0.72      0.70      0.71       231
weighted avg       0.73      0.74      0.73       231

Confusion Matrix 
[[124  22]
 [ 38  47]]


In [17]:
#2. Bootstrapping
#A. Bagging  B. Pasting   C. Random forest


In [18]:
#1. Bagging : call class BaggingClassifier
from sklearn.ensemble import BaggingClassifier

In [19]:
#create object of BaggingClassifier inbuilt class
bc=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=20,random_state=1)
#first pass parameter in the function : - we need to pass what type of algorithm be need to use ,suppose 
#we choose to use Logistic regression algo.
#second parameter : - how many algorithm means select n_estimators=10 means we want to 
#10 logistic regression ,
#third parameter : There are 10 logistic regression algo. and each of them will be train on 10
#samples may be 100 (10*10=100)

In [20]:
#call function
bc=create_model(bc)

              precision    recall  f1-score   support

           0       0.82      0.86      0.84       146
           1       0.73      0.68      0.71        85

    accuracy                           0.79       231
   macro avg       0.78      0.77      0.77       231
weighted avg       0.79      0.79      0.79       231

Confusion Matrix 
[[125  21]
 [ 27  58]]


In [21]:
#Pasting 
#create object of BaggingClassifier inbuilt class
bc1=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=50,random_state=1,
                      bootstrap=False) #by default bootstrap parameter=True means use Bagging
#if pass value in parameter bootstrap=False then use pasting

In [22]:
#call function
bc1=create_model(bc1)

              precision    recall  f1-score   support

           0       0.79      0.90      0.84       146
           1       0.77      0.59      0.67        85

    accuracy                           0.78       231
   macro avg       0.78      0.74      0.75       231
weighted avg       0.78      0.78      0.78       231

Confusion Matrix 
[[131  15]
 [ 35  50]]


In [30]:
#4. Stacking : -  This is Ensembling technique
#call mlxtend package : StackingClassifier inbuilt class
from mlxtend.classifier import StackingClassifier

In [31]:
#create object of LogisticRegression
lr=LogisticRegression()
#create object of DecisionTreeClassifier with gini index
dt1=DecisionTreeClassifier() #befault gini index
#create object of DecisionTreeClassifier with entropy
dt2=DecisionTreeClassifier(criterion="entropy")

In [32]:
#Create the model list 
model_list=[lr,dt1,dt2]
#4th class : it is meta classifier : LogisticRegression  , create object  of meta classifier class
meta=LogisticRegression()  #it is used for meta classifier 

In [33]:
#create the object of StackingClassifier class
sc=StackingClassifier(classifiers=model_list,meta_classifier=meta)

In [34]:
#Now , we train and test the model and generate classification report and confusion matrix 
#then call function
sc=create_model(sc)

              precision    recall  f1-score   support

           0       0.77      0.83      0.80       146
           1       0.66      0.58      0.62        85

    accuracy                           0.74       231
   macro avg       0.72      0.70      0.71       231
weighted avg       0.73      0.74      0.73       231

Confusion Matrix 
[[121  25]
 [ 36  49]]


In [35]:
#create object of BaggingClassifier inbuilt class but we choose Algo. DecisionTreeClassifier() means
#gini index means it is called random forest tree
rft=BaggingClassifier(DecisionTreeClassifier(),n_estimators=10,max_samples=2,random_state=1)

In [36]:
#call function
rft=create_model(rft)

              precision    recall  f1-score   support

           0       0.63      1.00      0.77       146
           1       0.00      0.00      0.00        85

    accuracy                           0.63       231
   macro avg       0.32      0.50      0.39       231
weighted avg       0.40      0.63      0.49       231

Confusion Matrix 
[[146   0]
 [ 85   0]]


In [37]:
#RandomForestClassifier : inbuilt class for randomforest , call RandomForestClassifier class means
#always use decisiontreeclassifier means select imp features from dataset to predict the output
from sklearn.ensemble import RandomForestClassifier

In [38]:
#create object of RandomForestClassifier class
rf=RandomForestClassifier(n_estimators=10,max_features =2,random_state=1)

In [39]:
#call function
rf=create_model(rf)

              precision    recall  f1-score   support

           0       0.80      0.90      0.85       146
           1       0.78      0.61      0.68        85

    accuracy                           0.79       231
   macro avg       0.79      0.75      0.76       231
weighted avg       0.79      0.79      0.79       231

Confusion Matrix 
[[131  15]
 [ 33  52]]
