In [24]:
#SVM :  it is classification Supervised Machine Learning Algorithm .
#Support vector mactor , It is used to classify yes or no , 1 or 0 or multiclass classifier 
#means its classified categoricl data 
#we use dataset heart.csv

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [25]:
#to load dataset 
df=pd.read_csv("heart.csv")

In [26]:
#to show first 5 records from dataset
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [27]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [28]:
#check null values
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [29]:
df.info()  #to show all details of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [30]:
#separate X and Y means Input and output (Labelled means target)
X=df.drop("target",axis=1) #input features
Y=df["target"] #output means target which want to predict

In [31]:
#Train_Test_Split : 70% & 30%
from sklearn.model_selection import train_test_split

#Split our dataset in train test of 70% & 30%
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [32]:
#create the function for train ,test and generate report
def create_model(model):
    model.fit(X_train,Y_train)
    Y_pred=model.predict(X_test)
    print(classification_report(Y_test,Y_pred))
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [33]:
#Base Line model : -  use LogisticRegression so call this class
from sklearn.linear_model import LogisticRegression

In [34]:
#Create the object of LogisticRegression class
lr=LogisticRegression() 

In [35]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [36]:
#call funcution
lr=create_model(lr)

              precision    recall  f1-score   support

           0       0.81      0.73      0.77        41
           1       0.80      0.86      0.83        50

    accuracy                           0.80        91
   macro avg       0.80      0.80      0.80        91
weighted avg       0.80      0.80      0.80        91

[[30 11]
 [ 7 43]]


In [37]:
#Support Vector machine
#Linear kernel function
#call class
from sklearn.svm import LinearSVC 

In [38]:
#create the object of inbuilt class LinearSVC 
svc=LinearSVC(random_state=1)

In [39]:
#call function
create_model(svc)

              precision    recall  f1-score   support

           0       0.46      1.00      0.63        41
           1       1.00      0.04      0.08        50

    accuracy                           0.47        91
   macro avg       0.73      0.52      0.35        91
weighted avg       0.76      0.47      0.33        91

[[41  0]
 [48  2]]


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=1, tol=0.0001,
          verbose=0)

In [40]:
#Apply soft margin means add externally error on training time
#create the object of inbuilt class LinearSVC  and passing parameter C for error
svc1=LinearSVC(random_state=1,C=0.5) #here C inbuilt parameter which pass the value =0.5 (0.1 to 1 )

In [41]:
#call function again we train ,test and check the score after add external error on training time
create_model(svc1)

              precision    recall  f1-score   support

           0       0.53      1.00      0.69        41
           1       1.00      0.28      0.44        50

    accuracy                           0.60        91
   macro avg       0.77      0.64      0.57        91
weighted avg       0.79      0.60      0.55        91

[[41  0]
 [36 14]]


LinearSVC(C=0.5, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=1, tol=0.0001,
          verbose=0)

In [42]:
#2. polynomial Kernel function of SVM so, use inbuilt class SVC
from sklearn.svm import SVC 
#SVC inbuilt class for non-linear data

In [43]:
#create object of SVC class for non linear whose kernel methode use : (polynomial)
poly_svc=SVC(random_state=1,kernel="poly") #use parameter kernel and pass ="poly" if apply polynomial
#kernel function

In [44]:
#call function
create_model(poly_svc)

              precision    recall  f1-score   support

           0       0.59      0.54      0.56        41
           1       0.65      0.70      0.67        50

    accuracy                           0.63        91
   macro avg       0.62      0.62      0.62        91
weighted avg       0.62      0.63      0.62        91

[[22 19]
 [15 35]]


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [45]:
#Radial Basis kernel function for use non-linear data
#create object of SVC class for non linear whose kernel methode use : (polynomial)
radial_svc=SVC(random_state=1,kernel="rbf") #use parameter kernel and pass ="rbf" if apply radial
#basis kernel function

In [46]:
#call function
create_model(radial_svc)

              precision    recall  f1-score   support

           0       0.59      0.46      0.52        41
           1       0.63      0.74      0.68        50

    accuracy                           0.62        91
   macro avg       0.61      0.60      0.60        91
weighted avg       0.61      0.62      0.61        91

[[19 22]
 [13 37]]


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
#in this dataset , better result got in Radial Basis kernel function and also clear we have(heart.csv) 
#non-linear dataset