In [1]:
#SVM :  it is classification Supervised Machine Learning Algorithm .
#Support vector mactor , It is used to classify yes or no , 1 or 0 or multiclass classifier 
#means its classified categoricl data 
#we use dataset mobile.csv

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#to load dataset 
df=pd.read_csv("mobile.csv")

In [3]:
#to show first 5 records from dataset
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            0  
1        1             1     0            1  
2        1             1     0            1  
3        1             0     0            1  
4        1             1     0            0  

[5 rows x 21 columns]

In [4]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [5]:
#Problem case study : - 
''' Basically company wants to launch their smart phone into the market , But they want to take 
a decision  whether they should keep the price more than 50000 or less than 50000 / - then It is 
the premium phone and it is less than 50000 than it is the normal phone .'''

#here target variable:  price_range  Whether the phone is premium means
#price_range>50000 or normal phone means price_range<50000 so that my target
#price_range=0 means <50000 and price_range=1 means >50000

' Basically company wants to launch their smart phone into the market , But they want to take \na decision  whether they should keep the price more than 50000 or less than 50000 / - then It is \nthe premium phone and it is less than 50000 than it is the normal phone .'

In [6]:
#check null values
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [7]:
df.info()  #to show all details of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [8]:
#separate X and Y means Input and output (Labelled means target)
X=df.drop("price_range",axis=1) #input features
Y=df["price_range"] #output means target which want to predict

In [9]:
#Train_Test_Split : 70% & 30%
from sklearn.model_selection import train_test_split

#Split our dataset in train test of 70% & 30%
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [10]:
#create the function for train ,test and generate report
def create_model(model):
    model.fit(X_train,Y_train)
    Y_pred=model.predict(X_test)
    print(classification_report(Y_test,Y_pred))
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [11]:
#Base Line model : -  use LogisticRegression so call this class
from sklearn.linear_model import LogisticRegression

In [12]:
#Create the object of LogisticRegression class
lr=LogisticRegression() 

In [13]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [14]:
#call funcution
lr=create_model(lr)

              precision    recall  f1-score   support

           0       0.88      0.89      0.89       284
           1       0.90      0.89      0.90       316

    accuracy                           0.89       600
   macro avg       0.89      0.89      0.89       600
weighted avg       0.89      0.89      0.89       600

[[254  30]
 [ 35 281]]


In [15]:
#Support Vector machine : -
#Use SVM : support vector machine : this is a classification supervised learning
#algo.
'''There are various kernel functions :
1. Linear Kernel function (use linear separated data)
2. polynomial kernel function (non-linearly)
3. radial basis kernel function (non-linearly)'''

'There are various kernel functions :\n1. Linear Kernel function (use linear separated data)\n2. polynomial kernel function (non-linearly)\n3. radial basis kernel function (non-linearly)'

In [16]:
#1. Linear Kernel (use linear separated data) function means data are easily separatable with
#the help of straight line  , this straight line is called decision boundary or hyperplane 

In [17]:
#Linear kernel function
#call class
from sklearn.svm import LinearSVC 

In [18]:
#create the object of inbuilt class LinearSVC 
svc=LinearSVC(random_state=1)

In [19]:
#call function
create_model(svc)

              precision    recall  f1-score   support

           0       0.54      1.00      0.70       284
           1       0.99      0.24      0.39       316

    accuracy                           0.60       600
   macro avg       0.76      0.62      0.54       600
weighted avg       0.78      0.60      0.54       600

[[283   1]
 [240  76]]


LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=1, tol=0.0001,
          verbose=0)

In [20]:
#score not bad but try its better 
#Apply soft margin means add externally error on training time
#create the object of inbuilt class LinearSVC  and passing parameter C for error
svc1=LinearSVC(random_state=1,C=0.5) #here C inbuilt parameter which pass the value =0.5 (0.1 to 1 )

In [21]:
#call function again we train ,test and check the score after add external error on training time
create_model(svc1)

              precision    recall  f1-score   support

           0       0.54      1.00      0.70       284
           1       0.99      0.24      0.39       316

    accuracy                           0.60       600
   macro avg       0.76      0.62      0.54       600
weighted avg       0.78      0.60      0.54       600

[[283   1]
 [240  76]]


LinearSVC(C=0.5, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=1, tol=0.0001,
          verbose=0)

In [22]:
#Here if add external error on runtime but no changes in score means no effect on score
#means we have data is non-linear data  , not linear dataset 
#So we will use polynomial kernel function means increase the dimension means if plot 1D then
#converting into 2D dimension and so on .

In [23]:
#2. polynomial Kernel function of SVM so, use inbuilt class SVC
from sklearn.svm import SVC 
#SVC inbuilt class for non-linear data

In [24]:
#create object of SVC class for non linear whose kernel methode use : (polynomial)
poly_svc=SVC(random_state=1,kernel="poly") #use parameter kernel and pass ="poly" if apply polynomial
#kernel function

In [25]:
#call function
create_model(poly_svc)

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       284
           1       0.98      0.98      0.98       316

    accuracy                           0.98       600
   macro avg       0.98      0.98      0.98       600
weighted avg       0.98      0.98      0.98       600

[[279   5]
 [  6 310]]


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [26]:
#Radial Basis kernel function for use non-linear data
#create object of SVC class for non linear whose kernel methode use : (polynomial)
radial_svc=SVC(random_state=1,kernel="rbf") #use parameter kernel and pass ="rbf" if apply radial
#basis kernel function

In [27]:
#call function
create_model(radial_svc)

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       284
           1       0.99      0.97      0.98       316

    accuracy                           0.98       600
   macro avg       0.98      0.98      0.98       600
weighted avg       0.98      0.98      0.98       600

[[280   4]
 [ 10 306]]


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
#in this dataset , better result got in polynomial kernel function and also clear we have(mobile.csv) 
#non-linear dataset